/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "stack_check.ts" instead.
 */

#include <check.h>

#line 1 "stack_check.ts"
#include <stdio.h>
#include "stack.h"

START_TEST(stack_create_bad_size)
{
#line 5
   Stack_t *sp;

   printf("stack_create_bad_size\n");
   
   sp = StackCreate(0, stack_int);
   fail_unless(sp == NULL, "bad size create failed");   

}
END_TEST

START_TEST(stack_create_int_positive)
{
#line 13
   Stack_t *sp;

   printf("stack_create_positive\n");

   sp = StackCreate(5, stack_int);
   fail_unless(sp != NULL, "positive create failed");   

}
END_TEST

START_TEST(stack_create_double_positive)
{
#line 21
   Stack_t *sp;

   printf("stack_create_double_positive\n");

   sp = StackCreate(5, stack_double);
   fail_unless(sp != NULL, "positive create failed");   

}
END_TEST

START_TEST(push_negative_no_stack)
{
#line 29
   Stack_t *sp = (Stack_t*)NULL;

   printf("push_negative_no_stack\n");
   
   fail_unless(push(sp,101) == -1, "push no stack failed");   

}
END_TEST

START_TEST(push_positive_with_stack)
{
#line 36
   Stack_t *sp = (Stack_t*)NULL;

   printf("push_positive_no_stack\n");
   
   sp = StackCreate(4, stack_int);
   fail_unless(push(sp,101) ==  0, "push with stack failed");   

}
END_TEST

START_TEST(push_object_type_char)
{
#line 44
   Stack_t *sp = (Stack_t*)NULL;
   char ret;
   int error;
   
   sp = StackCreate(2, stack_char);
   push(sp, 'A');
   push(sp, 'B');
   StackDump(sp, 0);
   error = top(sp, &ret);
   
   fail_unless(ret == 'B', "push char failed!");

}
END_TEST

START_TEST(push_object_type_float)
{
#line 57
   Stack_t *sp = (Stack_t*)NULL;
   float ret;
   int error;
   
   sp = StackCreate(2, stack_char);
   push(sp, 1.2);
   push(sp, 1.3);

   error = top(sp, &ret);
   
   fail_unless(ret != 1.3, "push char failed!");

}
END_TEST

START_TEST(push_positive_with_stack_beyond_limit)
{
#line 70
   Stack_t *sp = (Stack_t*)NULL;

   printf("push_positive_with_stack_beyond_limit\n");
   
   sp = StackCreate(2, stack_int);
   fail_unless(push(sp,101) == 0, "push fail");
   fail_unless(push(sp,102) == 0, "push fail");      
   fail_unless(push(sp,103) == -1, "push beyond limit");


}
END_TEST

START_TEST(pop_negative_no_stack)
{
#line 81
   Stack_t *sp = (Stack_t*)NULL;
   int ret;
   int error;
//   push(sp, 101);

   error = pop(sp,&ret);
   fail_unless(error == -1, "pop no stack failed");   

}
END_TEST

START_TEST(pop_negative_with_stack_no_push)
{
#line 90
   Stack_t *sp = (Stack_t*)NULL;
   int ret;
   int error;

   error = pop(sp,&ret);
   fail_unless(error == -1, "pop no pushes failed");   

}
END_TEST

START_TEST(pop_positive_with_stack)
{
#line 98
   Stack_t *sp;
   int ret;
   int error;

   sp = StackCreate(5, stack_int);
   
   push(sp, 101);
   
   error = pop(sp,&ret);
   fail_unless(ret == 101, "pop failed");   

}
END_TEST

START_TEST(top_positive_with_stack)
{
#line 110
   Stack_t *sp;
   int ret;
   int error;
   
   sp = StackCreate(5, stack_int);
   push(sp, 101);

   error = top(sp, &ret);
   fail_unless(error != -1, "top with stack failed");   

}
END_TEST

START_TEST(top_negative_null_stack)
{
#line 121
   int ret;
   int error;
   Stack_t *sp = NULL;
   sp = StackCreate(5, stack_int);

   error = top(sp,&ret);
   fail_unless(error == -1, "top with empty stack failed");   

}
END_TEST

START_TEST(top_negative_empty_stack)
{
#line 130
   Stack_t *sp = NULL;
   int ret;
   int error;

   error = top(sp, &ret);
   fail_unless(error == -1, "top with no stack failed");   

}
END_TEST

START_TEST(empty_postive__not_empty_stack)
{
#line 138
   Stack_t *sp = NULL;
   sp = StackCreate(5, stack_int);

   (void)push(sp,400);
   (void)push(sp,500);
   (void)push(sp,600);
   (void)push(sp,700);

   fail_unless(empty(sp) == 0, "empty with not empty stack");   

}
END_TEST

START_TEST(empty_negatve_empty_stack)
{
#line 149
   Stack_t *sp = NULL;

   sp = StackCreate(5, stack_int);
   fail_unless(empty(sp) == 1, "empty with empty stack");   

}
END_TEST

START_TEST(destroy_stack_no_stack)
{
#line 155
   Stack_t *sp = NULL;

   fail_unless(StackDestroy(sp) == -1, "Destroy failed, no stack created");


}
END_TEST

START_TEST(stack_swap_same_size)
{
#line 161
   Stack_t *sp;
   Stack_t *sp1;
   int error;
   int ret;
   
   sp  = StackCreate(4, stack_int);
   sp1 = StackCreate(4, stack_int);
   
   (void)push(sp,400);
   (void)push(sp,500);
   (void)push(sp,600);
   (void)push(sp,700);

   (void)push(sp1,402);
   (void)push(sp1,502);
   (void)push(sp1,602);
   (void)push(sp1,702);

   StackDump(sp,0);
   swap(sp, sp1);
   StackDump(sp,0);
   
   error = top(sp, &ret);
   fail_unless(ret == 702, "swap did not work!");
   
   error = top(sp1, &ret);
   fail_unless(ret == 700, "swap did not work!");

}
END_TEST

START_TEST(stack_swap_src_size_delta)
{
#line 190
   Stack_t *sp;
   Stack_t *sp1;
   int error;
   int ret;
   
   sp  = StackCreate(2, stack_int);
   sp1 = StackCreate(3, stack_int);
   
   (void)push(sp,400);
   (void)push(sp,500);

   (void)push(sp1,402);
   (void)push(sp1,502);
   (void)push(sp1,602);

   StackDump(sp,0);
   swap(sp, sp1);
   StackDump(sp,0);
   
   fail_unless(size(sp) == 3, "Src size didnt change");
   error = top(sp, &ret);
   fail_unless(ret == 602, "swap did not work!");
   
   error = top(sp1, &ret);
   fail_unless(ret == 500, "swap did not work!");

}
END_TEST

START_TEST(stack_swap_dst_size_delta)
{
#line 217
   Stack_t *sp;
   Stack_t *sp1;
   int error;
   int ret;
   
   sp  = StackCreate(3, stack_int);
   sp1 = StackCreate(2, stack_int);
   
   (void)push(sp,400);
   (void)push(sp,500);
   (void)push(sp,600);   

   (void)push(sp1,402);
   (void)push(sp1,502);

   StackDump(sp,0);
   swap(sp, sp1);
   StackDump(sp,0);
   
   fail_unless(size(sp1) == 3, "dst size did not change");
   error = top(sp, &ret);
   fail_unless(ret == 502, "swap did not work!");
   
   error = top(sp1, &ret);
   StackDump(sp1,0);   
   fail_unless(ret == 600, "swap did not work!");
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, stack_create_bad_size);
    tcase_add_test(tc1_1, stack_create_int_positive);
    tcase_add_test(tc1_1, stack_create_double_positive);
    tcase_add_test(tc1_1, push_negative_no_stack);
    tcase_add_test(tc1_1, push_positive_with_stack);
    tcase_add_test(tc1_1, push_object_type_char);
    tcase_add_test(tc1_1, push_object_type_float);
    tcase_add_test(tc1_1, push_positive_with_stack_beyond_limit);
    tcase_add_test(tc1_1, pop_negative_no_stack);
    tcase_add_test(tc1_1, pop_negative_with_stack_no_push);
    tcase_add_test(tc1_1, pop_positive_with_stack);
    tcase_add_test(tc1_1, top_positive_with_stack);
    tcase_add_test(tc1_1, top_negative_null_stack);
    tcase_add_test(tc1_1, top_negative_empty_stack);
    tcase_add_test(tc1_1, empty_postive__not_empty_stack);
    tcase_add_test(tc1_1, empty_negatve_empty_stack);
    tcase_add_test(tc1_1, destroy_stack_no_stack);
    tcase_add_test(tc1_1, stack_swap_same_size);
    tcase_add_test(tc1_1, stack_swap_src_size_delta);
    tcase_add_test(tc1_1, stack_swap_dst_size_delta);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
