/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "stack_test.ts" instead.
 */

#include <check.h>

#line 1 "stack_test.ts"
#include "stack.h"

START_TEST(pop)
{
#line 4
   stack_t *sp;
   sp = StackCreate(5);
   push(sp, 101);

   fail_unless(pop(sp) != -1, "pop failed");   
   
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, pop);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
