/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "stack_check.ts" instead.
 */

#include <check.h>

#line 1 "stack_check.ts"
#include <stdio.h>
#include "stack.h"

START_TEST(create_negative)
{
#line 5
   Stack_t *sp;

   printf("create_negative\n");
   
   sp = StackCreate(-1);
   fail_unless(sp == NULL, "negative create failed");   

}
END_TEST

START_TEST(create_positive)
{
#line 13
   Stack_t *sp;

   printf("create_positive\n");

   sp = StackCreate(5);
   fail_unless(sp != NULL, "positive create failed");   

}
END_TEST

START_TEST(push_negative_no_stack)
{
#line 21
   Stack_t *sp = (Stack_t*)NULL;

   printf("push_negative_no_stack\n");
   
   fail_unless(push(sp,101) == -1, "push no stack failed");   

}
END_TEST

START_TEST(push_positive_with_stack)
{
#line 28
   Stack_t *sp = (Stack_t*)NULL;

   printf("push_positive_no_stack\n");
   
   sp = StackCreate(4);
   fail_unless(push(sp,101) ==  0, "push with stack failed");   

}
END_TEST

START_TEST(push_positive_with_stack_beyond_limit)
{
#line 36
   Stack_t *sp = (Stack_t*)NULL;

   printf("push_positive_with_stack_beyond_limit\n");
   
   sp = StackCreate(2);
   fail_unless(push(sp,101) == 0, "push fail");
   fail_unless(push(sp,102) == 0, "push fail");      
   fail_unless(push(sp,103) == -1, "push beyond limit");
   
}
END_TEST

START_TEST(pop_negative_no_stack)
{
#line 46
   Stack_t *sp = (Stack_t*)NULL;
   push(sp, 101);

   fail_unless(pop(sp) == -1, "pop no stack failed");   

}
END_TEST

START_TEST(pop_negative_with_stack_no_push)
{
#line 52
   Stack_t *sp = (Stack_t*)NULL;

   fail_unless(pop(sp) == -1, "pop no pushes failed");   

}
END_TEST

START_TEST(pop_positive_with_stack)
{
#line 57
   Stack_t *sp;
   sp = StackCreate(5);
   push(sp, 101);

   fail_unless(pop(sp) == 101, "pop failed");   

}
END_TEST

START_TEST(top_positive_with_stack)
{
#line 64
   Stack_t *sp;
   sp = StackCreate(5);
   push(sp, 101);

   fail_unless(top(sp) != -1, "top with stack failed");   

}
END_TEST

START_TEST(top_negative_null_stack)
{
#line 71
   Stack_t *sp = NULL;
   sp = StackCreate(5);

   fail_unless(top(sp) == -1, "top with empty stack failed");   

}
END_TEST

START_TEST(top_negative_empty_stack)
{
#line 77
   Stack_t *sp = NULL;

   fail_unless(top(sp) == -1, "top with no stack failed");   

}
END_TEST

START_TEST(empty_postive__not_empty_stack)
{
#line 82
   Stack_t *sp = NULL;
   sp = StackCreate(5);

   (void)push(sp,400);
   (void)push(sp,500);
   (void)push(sp,600);
   (void)push(sp,700);

   fail_unless(empty(sp) == 0, "empty with not empty stack");   

}
END_TEST

START_TEST(empty_negatve_empty_stack)
{
#line 93
   Stack_t *sp = NULL;

   sp = StackCreate(5);
   fail_unless(empty(sp) == 1, "empty with empty stack");   

}
END_TEST

START_TEST(destroy_stack_no_stack)
{
#line 99
   Stack_t *sp = NULL;

   fail_unless(StackDestroy(sp) == -1, "Destroy failed, no stack created");   
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, create_negative);
    tcase_add_test(tc1_1, create_positive);
    tcase_add_test(tc1_1, push_negative_no_stack);
    tcase_add_test(tc1_1, push_positive_with_stack);
    tcase_add_test(tc1_1, push_positive_with_stack_beyond_limit);
    tcase_add_test(tc1_1, pop_negative_no_stack);
    tcase_add_test(tc1_1, pop_negative_with_stack_no_push);
    tcase_add_test(tc1_1, pop_positive_with_stack);
    tcase_add_test(tc1_1, top_positive_with_stack);
    tcase_add_test(tc1_1, top_negative_null_stack);
    tcase_add_test(tc1_1, top_negative_empty_stack);
    tcase_add_test(tc1_1, empty_postive__not_empty_stack);
    tcase_add_test(tc1_1, empty_negatve_empty_stack);
    tcase_add_test(tc1_1, destroy_stack_no_stack);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
