/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "stack_check.ts" instead.
 */

#include <check.h>

#line 1 "stack_check.ts"
#include <stdio.h>
#include "stack.h"

START_TEST(stack_create_bad_size)
{
#line 5
   Stack_t *sp;

   printf("stack_create_bad_size\n");
   
   sp = StackCreate(0, stack_int);
   fail_unless(sp == NULL, "bad size create failed");   

}
END_TEST

START_TEST(stack_create_int_positive)
{
#line 13
   Stack_t *sp;

   printf("stack_create_positive\n");

   sp = StackCreate(5, stack_int);
   fail_unless(sp != NULL, "positive create failed");   

}
END_TEST

START_TEST(stack_create_double_positive)
{
#line 21
   Stack_t *sp;

   printf("stack_create_double_positive\n");

   sp = StackCreate(5, stack_double);
   fail_unless(sp != NULL, "positive create failed");   

}
END_TEST

START_TEST(push_negative_no_stack)
{
#line 29
   Stack_t *sp = (Stack_t*)NULL;

   printf("push_negative_no_stack\n");
   
   fail_unless(push(sp,101) == -1, "push no stack failed");   

}
END_TEST

START_TEST(push_positive_with_stack)
{
#line 36
   Stack_t *sp = (Stack_t*)NULL;

   printf("push_positive_no_stack\n");
   
   sp = StackCreate(4, stack_int);
   fail_unless(push(sp,101) ==  0, "push with stack failed");   

}
END_TEST

START_TEST(push_positive_with_stack_beyond_limit)
{
#line 44
   Stack_t *sp = (Stack_t*)NULL;

   printf("push_positive_with_stack_beyond_limit\n");
   
   sp = StackCreate(2, stack_int);
   fail_unless(push(sp,101) == 0, "push fail");
   fail_unless(push(sp,102) == 0, "push fail");      
   fail_unless(push(sp,103) == -1, "push beyond limit");
   
}
END_TEST

START_TEST(pop_negative_no_stack)
{
#line 54
   Stack_t *sp = (Stack_t*)NULL;
//   push(sp, 101);

   fail_unless(pop(sp) == -1, "pop no stack failed");   

}
END_TEST

START_TEST(pop_negative_with_stack_no_push)
{
#line 60
   Stack_t *sp = (Stack_t*)NULL;

   fail_unless(pop(sp) == -1, "pop no pushes failed");   

}
END_TEST

START_TEST(pop_positive_with_stack)
{
#line 65
   Stack_t *sp;
   sp = StackCreate(5, stack_int);
   push(sp, 101);

   fail_unless(pop(sp) == 101, "pop failed");   

}
END_TEST

START_TEST(top_positive_with_stack)
{
#line 72
   Stack_t *sp;
   sp = StackCreate(5, stack_int);
   push(sp, 101);

   fail_unless(top(sp) != -1, "top with stack failed");   

}
END_TEST

START_TEST(top_negative_null_stack)
{
#line 79
   Stack_t *sp = NULL;
   sp = StackCreate(5, stack_int);

   fail_unless(top(sp) == -1, "top with empty stack failed");   

}
END_TEST

START_TEST(top_negative_empty_stack)
{
#line 85
   Stack_t *sp = NULL;

   fail_unless(top(sp) == -1, "top with no stack failed");   

}
END_TEST

START_TEST(empty_postive__not_empty_stack)
{
#line 90
   Stack_t *sp = NULL;
   sp = StackCreate(5, stack_int);

   (void)push(sp,400);
   (void)push(sp,500);
   (void)push(sp,600);
   (void)push(sp,700);

   fail_unless(empty(sp) == 0, "empty with not empty stack");   

}
END_TEST

START_TEST(empty_negatve_empty_stack)
{
#line 101
   Stack_t *sp = NULL;

   sp = StackCreate(5, stack_int);
   fail_unless(empty(sp) == 1, "empty with empty stack");   

}
END_TEST

START_TEST(destroy_stack_no_stack)
{
#line 107
   Stack_t *sp = NULL;

   fail_unless(StackDestroy(sp) == -1, "Destroy failed, no stack created");   
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, stack_create_bad_size);
    tcase_add_test(tc1_1, stack_create_int_positive);
    tcase_add_test(tc1_1, stack_create_double_positive);
    tcase_add_test(tc1_1, push_negative_no_stack);
    tcase_add_test(tc1_1, push_positive_with_stack);
    tcase_add_test(tc1_1, push_positive_with_stack_beyond_limit);
    tcase_add_test(tc1_1, pop_negative_no_stack);
    tcase_add_test(tc1_1, pop_negative_with_stack_no_push);
    tcase_add_test(tc1_1, pop_positive_with_stack);
    tcase_add_test(tc1_1, top_positive_with_stack);
    tcase_add_test(tc1_1, top_negative_null_stack);
    tcase_add_test(tc1_1, top_negative_empty_stack);
    tcase_add_test(tc1_1, empty_postive__not_empty_stack);
    tcase_add_test(tc1_1, empty_negatve_empty_stack);
    tcase_add_test(tc1_1, destroy_stack_no_stack);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
